version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: root1234

  alexandria-app-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  alexandria-app-frontend:
    build:
      context: ./frontend/alexandria-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - db