version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend # Path to your Spring project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend # Path to your Angular project
      dockerfile: Dockerfile
    ports:
      - "80:80"
