version: '3'
services:
  db:
    image: postgres:latest
    container_name: alexandria-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root1234
      POSTGRES_DB: postgres
      POSTGRES_URL: jdbc:postgresql://alexandria-db:5432/postgres
      SPRING_FLYWAY_URL: jdbc:postgresql://alexandria-db:5432/postgres
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root1234
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend # Path to your Spring project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres # Use the service name of the database container
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      SPRING_JPA_SHOW-SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
      SPRING_JPA_OPEN-IN-VIEW: false
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_URL: jdbc:postgresql://db:5432/postgres # Use the service name of the database container
      SPRING_FLYWAY_USER: root
      SPRING_FLYWAY_PASSWORD: root1234
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration/
      SPRING_FLYWAY_SCHEMAS: public
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: true

  frontend:
    build:
      context: ./frontend # Path to your Angular project
      dockerfile: Dockerfile
    ports:
      - "80:80"
